CREATE TABLE MOVIE_CAST (
    PERSON_ID VARCHAR2(50) NOT NULL,
    MOVIE_ID VARCHAR2(50) NOT NULL,
    CHARACTER_NAME VARCHAR2(255),
    CAST_ORDER NUMBER,
    CONSTRAINT PK_MOVIE_CAST PRIMARY KEY (PERSON_ID, MOVIE_ID)
);

ALTER TABLE MOVIE_CAST ADD CONSTRAINT FK_PERSON_TO_MOVIE_CAST
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (PERSON_ID)
ON DELETE CASCADE;

ALTER TABLE MOVIE_CAST ADD CONSTRAINT FK_MOVIE_TO_MOVIE_CAST
FOREIGN KEY (MOVIE_ID)
REFERENCES MOVIE (MOVIE_ID)
ON DELETE CASCADE;