CREATE TABLE MOVIE_GENRE (
    genreId NUMBER NOT NULL,
    movieId NUMBER NOT NULL,
    CONSTRAINT PK_MOVIE_GENRE PRIMARY KEY (genreId, movieId)
);

ALTER TABLE MOVIE_GENRE ADD CONSTRAINT FK_GENRE_TO_MOVIE_GENRE
FOREIGN KEY (genreId)
REFERENCES GENRE (genreId)
ON DELETE CASCADE;

ALTER TABLE MOVIE_GENRE ADD CONSTRAINT FK_MOVIE_TO_MOVIE_GENRE
FOREIGN KEY (movieId)
REFERENCES MOVIE (movieId)
ON DELETE CASCADE;