CREATE TABLE "MOVIE_CREW" (
	"person_id"	VARCHAR(50)		NOT NULL,
	"movie_id"	VARCHAR(50)		NOT NULL,
	"crew_job"	VARCHAR(100)		NULL
);

ALTER TABLE "MOVIE_CREW" 
ADD CONSTRAINT "PK_MOVIE_CREW" 
PRIMARY KEY ("person_id", "movie_id");

ALTER TABLE "MOVIE_CREW" 
ADD CONSTRAINT "FK_PERSON_TO_MOVIE_CREW_1"
FOREIGN KEY ("person_id")
REFERENCES "PERSON" ("person_id")
ON DELETE CASCADE;

ALTER TABLE "MOVIE_CREW" 
ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_CREW_1"
FOREIGN KEY ("movie_id")
REFERENCES "MOVIE" ("movie_id")
ON DELETE CASCADE;
