CREATE TABLE MOVIE_CREW (
    PERSON_ID NUMBER NOT NULL,
    MOVIE_ID NUMBER NOT NULL,
    CREW_JOB VARCHAR2(100),
    CONSTRAINT PK_MOVIE_CREW PRIMARY KEY (PERSON_ID, MOVIE_ID)
);

ALTER TABLE MOVIE_CREW ADD CONSTRAINT FK_PERSON_TO_MOVIE_CREW
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (PERSON_ID)
ON DELETE CASCADE;

ALTER TABLE MOVIE_CREW ADD CONSTRAINT FK_MOVIE_TO_MOVIE_CREW
FOREIGN KEY (MOVIE_ID)
REFERENCES MOVIE (MOVIE_ID)
ON DELETE CASCADE;