CREATE TABLE MOVIE (
    MOVIE_ID NUMBER NOT NULL,
    MOVIE_TITLE VARCHAR2(255),
    MOVIE_ORIGINAL_TITLE VARCHAR2(255),
    MOVIE_OVERVIEW CLOB,
    MOVIE_RELEASE_DATE DATE,
    MOVIE_RUNTIME NUMBER,
    MOVIE_POSTER_PATH VARCHAR2(255),
    MOVIE_BACKDROP_PATH VARCHAR2(255),
    MOVIE_RATING_AVERAGE NUMBER(5,2),
    MOVIE_RATING_COUNT NUMBER,
    MOVIE_CREATED_AT DATE,
    MOVIE_RECOMMEND_COUNT NUMBER DEFAULT 0, 
    CONSTRAINT PK_MOVIE PRIMARY KEY (MOVIE_ID)
);
