CREATE TABLE "MOVIE_CAST" (
	"person_id"	VARCHAR(50)		NOT NULL,
	"movie_id"	VARCHAR(50)		NOT NULL,
	"character_name"	VARCHAR(255)		NULL,
	"cast_order"	NUMBER(50)		NULL
);

ALTER TABLE "MOVIE_CAST" 
ADD CONSTRAINT "PK_MOVIE_CAST" 
PRIMARY KEY ("person_id", "movie_id");

ALTER TABLE "MOVIE_CAST" 
ADD CONSTRAINT "FK_PERSON_TO_MOVIE_CAST_1"
FOREIGN KEY ("person_id")
REFERENCES "PERSON" ("person_id")
ON DELETE CASCADE;

ALTER TABLE "MOVIE_CAST" 
ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_CAST_1"
FOREIGN KEY ("movie_id")
REFERENCES "MOVIE" ("movie_id")
ON DELETE CASCADE;

-- CHECK 제약 조건
ALTER TABLE "MOVIE_CAST"
ADD CONSTRAINT "CK_CAST_ORDER"
CHECK ("cast_order" IS NULL OR "cast_order" >= 0);
