CREATE TABLE MOVIE_CREW (
    personId NUMBER NOT NULL,
    movieId NUMBER NOT NULL,
    crewJob VARCHAR2(100),
    CONSTRAINT PK_MOVIE_CREW PRIMARY KEY (personId, movieId)
);

ALTER TABLE MOVIE_CREW ADD CONSTRAINT FK_PERSON_TO_MOVIE_CREW
FOREIGN KEY (personId)
REFERENCES PERSON (personId)
ON DELETE CASCADE;

ALTER TABLE MOVIE_CREW ADD CONSTRAINT FK_MOVIE_TO_MOVIE_CREW
FOREIGN KEY (movieId)
REFERENCES MOVIE (movieId)
ON DELETE CASCADE;

drop table MOVIE_CREW;