CREATE TABLE "MOVIE_GENRE" (
	"genre_id"	VARCHAR(50)		NOT NULL,
	"movie_id"	VARCHAR(50)		NOT NULL
);

ALTER TABLE "MOVIE_GENRE" 
ADD CONSTRAINT "PK_MOVIE_GENRE" 
PRIMARY KEY ("genre_id", "movie_id");

ALTER TABLE "MOVIE_GENRE" 
ADD CONSTRAINT "FK_GENRE_TO_MOVIE_GENRE_1"
FOREIGN KEY ("genre_id")
REFERENCES "GENRE" ("genre_id")
ON DELETE CASCADE;

ALTER TABLE "MOVIE_GENRE" 
ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_GENRE_1"
FOREIGN KEY ("movie_id")
REFERENCES "MOVIE" ("movie_id")
ON DELETE CASCADE;
