CREATE TABLE MOVIE_GENRE (
    GENRE_ID VARCHAR2(50) NOT NULL,
    MOVIE_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MOVIE_GENRE PRIMARY KEY (GENRE_ID, MOVIE_ID)
);

ALTER TABLE MOVIE_GENRE ADD CONSTRAINT FK_GENRE_TO_MOVIE_GENRE
FOREIGN KEY (GENRE_ID)
REFERENCES GENRE (GENRE_ID)
ON DELETE CASCADE;

ALTER TABLE MOVIE_GENRE ADD CONSTRAINT FK_MOVIE_TO_MOVIE_GENRE
FOREIGN KEY (MOVIE_ID)
REFERENCES MOVIE (MOVIE_ID)
ON DELETE CASCADE;