CREATE TABLE "MOVIE_SIMILAR" (
	"similar_movie_id"	VARCHAR(50)		NOT NULL,
	"movie_id"	VARCHAR(50)		NOT NULL
);

ALTER TABLE "MOVIE_SIMILAR" 
ADD CONSTRAINT "PK_MOVIE_SIMILAR" 
PRIMARY KEY ("similar_movie_id", "movie_id");

ALTER TABLE "MOVIE_SIMILAR" 
ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_SIMILAR_1"
FOREIGN KEY ("similar_movie_id")
REFERENCES "MOVIE" ("movie_id")
ON DELETE CASCADE;

ALTER TABLE "MOVIE_SIMILAR" 
ADD CONSTRAINT "FK_MOVIE_TO_MOVIE_SIMILAR_2"
FOREIGN KEY ("movie_id")
REFERENCES "MOVIE" ("movie_id")
ON DELETE CASCADE;
