CREATE TABLE MEMBER_MOVIE_RECOMMEND (
  memNo    NUMBER NOT NULL,
  movieId  NUMBER NOT NULL,
  CONSTRAINT pk_RECOMMEND PRIMARY KEY (memNo, movieId),
  CONSTRAINT fk_rec_member FOREIGN KEY (memNo) REFERENCES MEMBER(memNo),
  CONSTRAINT fk_rec_movie FOREIGN KEY (movieId) REFERENCES MOVIE(movieId)
);
