CREATE TABLE MEMBER_MOVIE_RECOMMEND (
  memNo    NUMBER NOT NULL,
  movieId  NUMBER NOT NULL,
  CONSTRAINT pk_RECOMMEND PRIMARY KEY (memNo, movieId),
  CONSTRAINT fk_rec_member FOREIGN KEY (memNo) REFERENCES MEMBER(memNo),
  CONSTRAINT fk_rec_movie FOREIGN KEY (movieId) REFERENCES MOVIE(movieId)
);

ALTER TABLE MEMBER_MOVIE_RECOMMEND
ADD recommendCreatedAt DATE DEFAULT SYSDATE;

CREATE INDEX idx_rec_date  
ON MEMBER_MOVIE_RECOMMEND (recommendCreatedAt, movieId);

ALTER TABLE MEMBER_MOVIE_RECOMMEND DROP CONSTRAINT fk_rec_movie;

ALTER TABLE MEMBER_MOVIE_RECOMMEND ADD CONSTRAINT fk_rec_movie
FOREIGN KEY (movieId)
REFERENCES MOVIE (movieId)
ON DELETE CASCADE;

