CREATE TABLE ADD_FILE
(
    FILENO     NUMBER               NOT NULL,
    BOARDID    NUMBER               NOT NULL,
    BOARDTYPE  NUMBER               NOT NULL,
    FILENAME   VARCHAR2(255)        NOT NULL,
    FILEPATH   VARCHAR2(500)        NOT NULL,
    FILESIZE   NUMBER               NOT NULL,
    UPLOADDATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ADD_FILE PRIMARY KEY (FILENO),
    CONSTRAINT FK_ADD_FILE_BOARD FOREIGN KEY (BOARDID, BOARDTYPE)
        REFERENCES BOARD (BOARDID, BOARDTYPE)
);

CREATE SEQUENCE FILE_NO_SEQ NOCACHE;

drop table ADD_FILE;