CREATE SEQUENCE SEQ_COMMENTS START WITH 1 INCREMENT BY 1;

CREATE TABLE COMMENTS
(
    COMMENTSID      NUMBER(10),              -- commentsId (PK)
    BOARDID         NUMBER(10)     NOT NULL, -- boardId
    BOARDTYPE       NUMBER(10)     NOT NULL, -- boardType
    COMMENTSCONTENT VARCHAR2(2000) NOT NULL, -- commentsContent
    COMMENTSNAME    VARCHAR2(50),            -- commentsName
    COMMENTSDATE    DATE DEFAULT SYSDATE,    -- commentsDate
    COMMENTSNO      NUMBER(10),              -- commentsNo
    MEMNO           NUMBER(10)     NOT NULL, -- memNo (FK 설정 대상)
    PARENTBOARDNO   NUMBER(10),              -- parentBoardNo (FK 설정 대상)
    PARENTBOARDID   NUMBER(10),              -- parentBoardId (FK 설정 대상)

    CONSTRAINT PK_COMMENTS PRIMARY KEY (COMMENTSID),

    CONSTRAINT FK_COMMENTS_BOARD FOREIGN KEY (BOARDID, BOARDTYPE)
        REFERENCES BOARD (BOARDID, BOARDTYPE),

    CONSTRAINT FK_COMMENTS_MEMBER FOREIGN KEY (MEMNO)
        REFERENCES MEMBER (MEMNO),

    CONSTRAINT FK_COMMENTS_PARENT_ID FOREIGN KEY (PARENTBOARDID)
        REFERENCES COMMENTS (COMMENTSID),

    CONSTRAINT FK_COMMENTS_PARENT_NO FOREIGN KEY (PARENTBOARDNO)
        REFERENCES COMMENTS (COMMENTSID)
);
/*기존 제약조건삭제*/
ALTER TABLE COMMENTS DROP CONSTRAINT FK_COMMENTS_PARENT_ID;

ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_PARENT_ID
    FOREIGN KEY (PARENTBOARDID) REFERENCES COMMENTS(COMMENTSID)
        ON DELETE CASCADE;

COMMIT;